name 'netmanagers-bacula'
version '1.1.0'

author 'Sebastian Quaino'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source 'https://github.com/netmanagers/puppet-bacula'
summary 'Puppet module for bacula'
description 'This module installs and manages bacula. Check README for details.'
dependency 'puppetlabs/stdlib', '>= 2.2.0'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
